### ISSUE TITLE
exposing the type t

### ISSUE THREAD

**Issue by hannesm** [ocamllabs/ocaml-integers#2]
would be useful, otherwise libraries who wish to use this one need to adapt their code (thinking about cstruct).  also, while in certain applications the wrapping behaviour is great to have, others need to know about overflows (I developed https://github.com/hannesm/usane for this) -- it would be great to have interoperability between cstruct, ocaml-integers, and usane (and this can be achieved by having the `type t = int` (or `int32` / `int64`) publicly exposed.

OTOH, I'm still not sure whether exposing this type is a good idea, you clearly loose local reasoning inside of the library (and thus safety guarantees).  but reimplementing all operations again (like `land`), once in the stdlib, and once more in ocaml-integers, looks like a bad idea to me.  also, in case cstruct will depend on ocaml-integers, there'd be a coercion dance needed to get each value into a non-wrapping representation.

thoughts?

**Comment by yallop** [comment]
For signed integers the types are [already exposed](https://github.com/ocamllabs/ocaml-integers/blob/644afd1738e60046b60fd621e4d74da5f087f232/src/signed.mli#L43-L50).

Exposing `type t = private int` for `UInt8` and `UInt16` is a possibility.

For the other unsigned integer types there's nothing to expose: `Uint32.t` and `UInt64.t` are implemented as custom types, not using `int32` and `int64`, so that polymorphic comparisons work correctly.

**Comment by yallop** [comment]
#4 exposes `UInt8.t`,  `UInt16.t` and `UChar.t` as `private int`.  I think that's all that can be exposed.
